# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-08 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.CharField(choices=[('01', '1:00 AM'), ('02', '2:00 AM'), ('03', '3:00 AM'), ('04', '4:00 AM'), ('05', '5:00 AM'), ('06', '6:00 AM'), ('07', '7:00 AM'), ('08', '8:00 AM'), ('09', '9:00 AM'), ('10', '10:00 AM'), ('11', '11:00 AM'), ('12', '12:00 PM'), ('13', '1:00 PM'), ('14', '2:00 PM'), ('15', '3:00 PM'), ('16', '4:00 PM'), ('17', '5:00 PM'), ('18', '6:00 PM'), ('19', '7:00 PM'), ('20', '8:00 PM'), ('21', '9:00 PM'), ('22', '10:00 PM'), ('23', '11:00 PM'), ('00', '12:00 AM')], max_length=2)),
                ('short_reason', models.CharField(max_length=15)),
                ('reason', models.TextField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
        ),
    ]
